import argparse

# -------------- ARGPARSE PARAMETERS -------------------------------------------
parser = argparse.ArgumentParser(description="Runs visualizer")

parser.add_argument('-input',
                    action='store',
                    required=True,
                    type=str,
                    help='''Input event stream (.txt file).
                    Should be a text with a .txt extension
                    Example: inputs/my_input.txt''',
                    metavar='REQUIRED str input_text_file')

parser.add_argument('-model',
                    action='store',
                    required=True,
                    type=str,
                    help='''Model Generated by the neural network
					File .ckpt''',
                    metavar='REQUIRED str ckpt_file')
